### ISSUE TITLE
advice sometimes fails

### ISSUE THREAD

**Issue by baer** [baer/eric-baer#2]
Looks like the answer json is not always as expected.

```
$ eric-baer advice
Hello! I'm a programmed to help people make hard decisions. Ask me anything!
whddup

TypeError: Cannot read property 'data' of undefined
    at Request._callback (/usr/local/lib/node_modules/eric-baer/lib/advice.js:23:53)
    at Request.self.callback (/usr/local/lib/node_modules/eric-baer/node_modules/request/request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/eric-baer/node_modules/request/request.js:1047:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/eric-baer/node_modules/request/request.js:998:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by baer** [comment]
Closed by https://github.com/baer/eric-baer/commit/9e735df951d56e38fb3fe35cf026e4d501d0a063
